### ISSUE TITLE
Rewriting the gateways

### ISSUE THREAD

**Issue by TimZ99** [phpservermon/phpservermon#588]
A few of the gateways are outdated and most of the implementations don't check on errors. It's time to rewrite them!

The implementations now return 1 for a successful SMS and the error message when it fails.
In the case that a gateway only requires an API key, the password field should be used. The field for the username will stay empty.

# ToDo
- [x] Clickatell - <https://www.clickatell.com>
- [x] Inetworx - <https://www.inetworx.ch>
- [x] Messagebird - <https://www.messagebird.com>
- [x] Mosms - <https://www.mosms.com>
- [x] Smsglobal - <https://smsglobal.com/>
- [x] SMSit - <https://www.smsit.dk/>
- [x] Spryng - <https://www.spryng.nl>
- [x] Textmarketer - <https://www.textmarketer.co.uk>
- [x] FreeVoipDeal - <https://www.freevoipdeal.com>
- [x] Nexmo - <https://www.nexmo.com/>
- [x] OctoPush - <https://www.octopush.com/>
- [x] FreeMobile (FR) - <https://mobile.free.fr/>
- [x] Twilio - <https://twilio.com>
- [x] CM Telecom - <https://www.cm.com/>
- [x] GatewayAPI (#585)  - <https://www.gatewayapi.com/>

**Comment by wardpieters** [comment]
[ClickSend](https://github.com/phpservermon/phpservermon/blob/develop/src/psm/Txtmsg/ClickSend.php) and [Smsgw](https://github.com/phpservermon/phpservermon/blob/develop/src/psm/Txtmsg/Smsgw.php) still need to be done, working on them right now.
